# Generated by Django 2.2.5 on 2020-02-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impression',
            name='comment',
            field=models.TextField(verbose_name='コメント'),
        ),
    ]
